### ISSUE TITLE
Image swap on hover

### ISSUE THREAD

**Issue by vivkay** [vivkay/donate#1]
Hi @thomasjbradley!

I'm building this fundraising website - trying to keep it simple. 

On the right side I have an image that I want to swap on hover (her expression changes). I want to keep the image setup like it is now (she's rappelling off the side of the page, so her rope needs to be behind the billboard at all times). 

I want to use jQuery to make the swap but people online are talking about using css and sprites -- and I'm confused (I tried making this a background image with a hover but the image disappeared and I don't know how to make this work... also it works well right now, so I'm hesitant to break everything!). Also I'm not sure how best to do this with jQuery - do you have a video for a mouseover image swap hidden somewhere?

Thanks!!

Viv

**Comment by vivkay** [comment]
Actually I'd love for her to translate downwards and swap image on hover... here are the images so you get an idea. 

Right now she has a css animation (swinging) - it gives the character a bit more life and encourages exploration/hover trigger event I think. Thus not sure if this would work as a background image anymore. 

So jquery it is!?

**Comment by vivkay** [comment]
![screen shot 2015-07-18 at 10 20 01 am](https://cloud.githubusercontent.com/assets/6340292/8761909/98b38e44-2d36-11e5-87c0-8c55dea214e6.png)

**Comment by thomasjbradley** [comment]
I don't think you should use jQuery; it's complete overkill. CSS sprites are definitely the best way.

I do have a video on using CSS sprites here:
http://learn-the-web.algonquindesign.ca/topics/using-images/#sprites

You could still add animations/transitions to the sprites if you want.

**Comment by vivkay** [comment]
Good to know! Thanks for this resource - I'm gonna sprite this baby up!

**Comment by vivkay** [comment]
(wish me luck!)

**Comment by vivkay** [comment]
Uh oh @thomasjbradley, this isn't working... I have no idea what I'm doing here!!

I get the general idea of a sprite working as a sort of clipping mask. So for hovering, is this right:

```
.sprite {
    width 100px;
    height: 100px;
    background-image: url(../images/rappel.png);
    background-repeat: no-repeat;
    background-position: 0 0;
}

.sprite:hover {
    background position: 0 -100;
}

```

But the positioning is hard for me to wrap my head around too now... the image was exactly where I wanted it before, and now it's cut off and on the wrong side of the screen?

```
<div class="rightcolumn">
      <div class="sprite"></div>
    </div>

```

**Comment by vivkay** [comment]
This is the right side column:

```
.right-column {
  overflow: hidden;
  float: right;
  width: 33.333%;
}
```

Is this a hard thing? Should I give up and just leave it as it was?? :(

**Comment by vivkay** [comment]
I also couldn't find a video on sprites on that link. But there's the video about image replacement - but that looks like it's just for text? :/

**Comment by vivkay** [comment]
And is this the way to build the sprite in illustrator? You mentioned photoshop, but I'm in AI anyway since it's all vector...?
![screen shot 2015-07-18 at 2 48 11 pm](https://cloud.githubusercontent.com/assets/6340292/8763090/217f1fde-2d5c-11e5-856a-0d7baed1b581.png)

**Comment by thomasjbradley** [comment]
This code here has two problems:

``` css
.sprite:hover {
    background position: 0 -100;
}
```
1. `background-position` is missing a dash
2. `-100` is missing a unit

---

Did you check out the playlist at the top?

![screen shot 2015-07-18 at 2 48 51 pm](https://cloud.githubusercontent.com/assets/105192/8763093/3e1b1a6c-2d5c-11e5-9916-baadae78fd7d.png)

**Comment by vivkay** [comment]
Ok thanks! watching the video now!!

**Comment by vivkay** [comment]
...is the theory the same if I do it in illustrator, or will that muck things up?

**Comment by thomasjbradley** [comment]
Exactly the same.

**Comment by vivkay** [comment]
Ok cool! 

So what's happening now is that my image is being cut off (and it's on the wrong side). I used background-color like you do in the video to see what's happening - and the whole sprite seems cut. Even though I changed the height and width. Any ideas why that's happening?

![screen shot 2015-07-18 at 2 56 17 pm](https://cloud.githubusercontent.com/assets/6340292/8763129/46443ca4-2d5d-11e5-868c-3bdf381efa18.png)

**Comment by vivkay** [comment]
(it's the pink bit)

**Comment by thomasjbradley** [comment]
Here's a new video that shows exactly what you want: https://www.youtube.com/watch?v=zoLaoLGblzc&index=14&list=PLWjCJDeWfDdewUQe57s3Tuktg_8eT0yA7

**Comment by vivkay** [comment]
you. are. amazinggggg

**Comment by vivkay** [comment]
you said you need to add inline-block to give it a width and height - is that where I broke it maybe?

**Comment by vivkay** [comment]
oh dear.. display: inline-block makes everything disappear. And this video helps me wrap my head around it, but something else is still ruining my page layout. :/

**Comment by vivkay** [comment]
I'm trying to play detective here... maybe does it have to be inside an a tag in the html (right now I kept it in a div)?

**Comment by vivkay** [comment]
Ok it disappeared again. 

This is my html

```
    <div class="rightcolumn">
      <a class="sprite" href="#"></a></a>
    </div>
```

And for CSS, I have 

```
.right-column {
  overflow: hidden;
  float: right;
  width: 33.333%;
}

.sprite {
    width 256px;
    height: 402px;
    background-image: transparent url(../images/rappel-sprite-01.png);
    background-repeat: no-repeat;
    background-position: 0 0;
    background-color: pink;
}

.sprite:hover {
    background position: 0 -402px;
}
```

**Comment by vivkay** [comment]
(also just added the dash to background-position at the hover state there)

**Comment by vivkay** [comment]
display: block makes it appear ...but still cut off :/

**Comment by vivkay** [comment]
And what's even WEIRDER is that the hover is working...but it's showing the wrong image. And no hovering shows nothing. Plus it's still cut weird and on the wrong side of the screen? :/

**Comment by vivkay** [comment]
(updated github so you can see)

**Comment by vivkay** [comment]
![200](https://cloud.githubusercontent.com/assets/6340292/8763198/97a61dcc-2d5f-11e5-95f1-ac655d9522e6.gif)

**Comment by vivkay** [comment]
oh dear oh dear...it all disappeared again. But now the space it occupies is larger.

**Comment by thomasjbradley** [comment]
I needed the display inline-block in the video because it was an `<a>` tag. If you're using a `<div>` then it’s already block.

**Comment by thomasjbradley** [comment]
The width and height of `.sprite` must match your image: 256 x 402.

**Comment by thomasjbradley** [comment]
Width maybe isn't too important, but height is.
Because your sprite is vertical the width is likely irrelevant.

**Comment by vivkay** [comment]
Hmm..the width and height of sprite match that. It's only the column that's 33% width (that's my  super simple grid).

**Comment by vivkay** [comment]
![screen shot 2015-07-18 at 3 37 30 pm](https://cloud.githubusercontent.com/assets/6340292/8763292/ec53d6f4-2d62-11e5-99d5-e6b1fc157b76.png)

This is what I'm seeing right now. I have no idea what is broken...:(

**Comment by thomasjbradley** [comment]
There's `.sprite` code in two places that are conflicting: "main.css" and "grid.css".

**Comment by vivkay** [comment]
I just deleted that too. :(

**Comment by vivkay** [comment]
It's now just in main.

**Comment by thomasjbradley** [comment]
The `background-image` declaration can't also specify `background-color`:
https://github.com/vivkay/donate/blob/gh-pages/css/main.css#L178

**Comment by vivkay** [comment]
Ok...I removed the color, but now it just appears blank.

**Comment by thomasjbradley** [comment]
Did you sync?

**Comment by vivkay** [comment]
I'm not sure if this is illustrator, but in AI my artboard is saying the sprite is 256x688 (and each image is 402px high). But my png shows a different dimension... :/

**Comment by vivkay** [comment]
just synced

**Comment by vivkay** [comment]
synched*

**Comment by vivkay** [comment]
![screen shot 2015-07-18 at 3 43 27 pm](https://cloud.githubusercontent.com/assets/6340292/8763310/c1f6bb1e-2d63-11e5-8255-deb199f7646d.png)

these are the dimensions brackets show when I hover over the full sprite

**Comment by vivkay** [comment]
I've been trying to code this "simple" page for about 8 hours now...if I send you a zipped file with my code would you be able to have a glance and see if you can fix this hover issue? I'm starting to lose hope!! (and my butt is getting sore sitting in one spot all day)

**Comment by vivkay** [comment]
Or maybe I'll just kill the hover idea for now. But I spent so long trying to make it work ahhhhhh

**Comment by thomasjbradley** [comment]
Don't send me the zip, I can just download it from GitHub.
Do send me your Illustrator file though.

**Comment by thomasjbradley** [comment]
There's still a background colour on this line:
https://github.com/vivkay/donate/blob/gh-pages/css/main.css#L178

**Comment by vivkay** [comment]
do you mean 'transparent' - is that a color?

**Comment by vivkay** [comment]
color property*

**Comment by thomasjbradley** [comment]
Sure is.

**Comment by vivkay** [comment]
ah yes indeed - that fixed that. Now the problems are:
- giant image 
- image not in right column (33% width)/fixed beside text

**Comment by vivkay** [comment]
Should I email you the illustrator file?

**Comment by thomasjbradley** [comment]
Yes, send the Illustrator file. I need to figure out what's wrong there.
I have it working otherwise.

**Comment by vivkay** [comment]
when I add the swing animation, thinks go funky too :/

**Comment by vivkay** [comment]
things*

**Comment by vivkay** [comment]
but that could also be just becuase the image is giant and funky itself at the moment...

**Comment by thomasjbradley** [comment]
Column issue: typo on this line.
https://github.com/vivkay/donate/blob/gh-pages/index.html#L52

**Comment by vivkay** [comment]
no way was it something that small. damnit brain!

**Comment by vivkay** [comment]
![screen shot 2015-07-18 at 4 04 37 pm](https://cloud.githubusercontent.com/assets/6340292/8763374/c4ffe026-2d66-11e5-8a8d-3a40a8ff5a38.png)
This is where I'm at...close. I think something strange happened when I exported from AI though.

**Comment by thomasjbradley** [comment]
Delete the side bits in Illustrator. Save a Copy as SVG. Make sure the settings match this dialog:
http://learn-the-web.algonquindesign.ca/topics/image-formats/#svg

**Comment by thomasjbradley** [comment]
Delete this line; it's broken anyways:
https://github.com/vivkay/donate/blob/gh-pages/css/main.css#L176

**Comment by vivkay** [comment]
YOU FIXED IT!

**Comment by vivkay** [comment]
Any idea how I can move the whole sprite up behind the hero a little bit more? Should I start the sprite reveal lower?
(her rope is disconnecting when she swings)

**Comment by vivkay** [comment]
![screen shot 2015-07-18 at 4 14 32 pm](https://cloud.githubusercontent.com/assets/6340292/8763415/1c93d440-2d68-11e5-9deb-348b6fb9a911.png)

**Comment by thomasjbradley** [comment]
It's probably that the -400px isn't the right number; try adjusting it.

**Comment by vivkay** [comment]
Darn. The sprite isn't fixed anymore either. Can I do this to the sprite?

**Comment by vivkay** [comment]
Or do I maybe need to wrap it in a new div and fix the div?

**Comment by vivkay** [comment]
(uh oh...trying to fix it makes it all disappear again)

**Comment by vivkay** [comment]
![200-2](https://cloud.githubusercontent.com/assets/6340292/8763435/13d6b3b2-2d69-11e5-8f9c-44b36632330c.gif)

**Comment by vivkay** [comment]
no good?

```
.fixed-container {
    position: fixed;
    right: 0;
}
```

**Comment by thomasjbradley** [comment]
Sync?

**Comment by vivkay** [comment]
synched...

**Comment by thomasjbradley** [comment]
What about putting a `top` or `z-index` on it?

**Comment by vivkay** [comment]
oh dear, I couldn't get that to work either. I've got to get this live soon to start raising funds...I've reverted to the single image for now. 

Is there something else I'm maybe missing to make the sprite work? It'd be so nice to have! :/

**Comment by vivkay** [comment]
I figured it out. Not with a sprite, but I'll save that for when I can ask you in person during the school year (I'll try experimenting with it beforehand too). 

THANKS @thomasjbradley 

I'm going to optimize for mobile tonight and then I would love to get your opinion...I added some bells and whistles that make me giggle.

:D
